### ISSUE TITLE
ariva.js

### ISSUE THREAD

**Issue by littleyoda** [mikekorb/JavaStockQuotes#3]
alltests return an Error for ariva.js

javax.script.ScriptException: TypeError: null has no such function "click" in <eval> at line number 76
    at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
    at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:389)
    at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
    at jsq.fetcher.history.GenericJSFetcher.prepare(GenericJSFetcher.java:70)
    at AllJSTests.runit(AllJSTests.java:90)

**Comment by littleyoda** [comment]
also all config options are missing

**Comment by mikekorb** [comment]
fixed
